name: my-docker-project

services:
  app:
    build: .
    image: my-app-image
    container_name: my-app-container
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./a_core/.env
    depends_on:
      - postgres
      - redis
   

  postgres:
    image: postgres
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    

  redis:
    image: "redis:alpine"
    container_name: my-redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data




volumes:
  postgres_data:
  redis_data:
